ARDUINO_DIR=/usr/share/arduino
ADMK_DIR=/home/andre/Development/arduino-make/Arduino-Makefile
AVR_TOOLS_DIR=/usr

BOARD_TAG = nano328
ARDUINO_LIBS=EEPROM panstamp
F_CPU=8000000L

include /home/andrej/Development/arduino-make/Arduino-Makefile/Arduino.mk
